server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantmanager
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet